apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vx19f6wb6-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vx19f6wb6-dotnet-basic-gitops